### ISSUE TITLE
annotations as indented bullet-points, below a task

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/vimwiki-pytasks#7]
Annotations can be logically presented/ created as indented list items, under a task. As long as the text-block remains contiguous, then annotations should not affect dependency/ hierarchy, 

* [X] continue testing twwiki                          #bfea17e6-778a-43e0-8508-a7d29b39673d
        * this is the first annotation
* [ ] stop screwing around with taskwarrior!                     #1c5f75ac-8fa6-4913-9305-3f63d21dcde5
        * [ ] take stats          #5e485bd4-576d-40c7-919f-7d02dbc6cf6b
        * [ ] test again Project thing              #ec44828b-e6b8-48f8-9815-43360f57e352
                * [ ] yet another test         #18206957-d35b-43e7-9177-5f20d95a0fc1
                        * annotation for above
                        * another bullet point/ ammotation
                * [ ] the last task  #30783ba1-4262-482c-a983-f7339512fb85

**Comment by tbabej** [comment]
I'm not sure I would want to implement this.

Currently we have a easy mapping: 1 task = 1 line. This allows for easy parsing, generation / deletion of tasks in viewports.

This would also have to be configurable, as I can imagine users with heavy annotation usage would want to hide this list.

In general, anything that changes the number of lines per task is going to be hard to implement unless this concept is generalized.

**Comment by linuxcaffe** [comment]
backlog!

**Comment by tbabej** [comment]
3 years later, I am generally open to this idea and would support its implementation.

**Comment by williamjameshandley** [comment]
I would also really appreciate this functionality. Do you have any estimate about how much work it would be to implement? If it is a matter of an afternoon, I would consider having a go just in order to better understand this extremely impressive plugin.

**Comment by ningsuhen** [comment]
I'm assuming the violation of 1 task = 1 line will introduce some complexities. Will it be simpler if we can implement this as a tooltip? perhaps using something like https://github.com/yshui/tooltip.nvim ? Not aware of a solution for regular Vim though.

**Comment by tbabej** [comment]
Tooltips would definitely work, and I guess I would be fine with that bonus functionality working only in `neovim`.

I'm assuming however, that in order for the tooltip to show, you need to hover over that line anyway - in which case, it wouldn't be that much different from hitting Enter to display the output of `task info` (`:TaskWikiInfo` command) :thinking:

**Comment by ningsuhen** [comment]
Agreed, also realized it would be read only which will work for my use case but not if someone wants to add the annotations easily as OP pointed out.

**Comment by salman69e27** [comment]
How would this work with child tasks? If I have a task that has both annotations and child tasks, will they look like this:

```
* [ ] Task1
    * Task1 annotation1
    * [ ] Child-task1
        * Child-task1 annotation1
    * [ ] Child-task2
    * Task1 annotation2
    * [ ] Child-task3
```

**Comment by tbabej** [comment]
There should be ways to work around that. For example, the annotations could be displayed first, followed by the child tasks:

```
* [ ] Task1
    * Task1 annotation1
    * Task1 annotation2
    * [ ] Child-task1
        * Child-task1 annotation1
    * [ ] Child-task2
    * [ ] Child-task3
```

**Comment by salman69e27** [comment]
And to do this we need to change the regex to match the task with all its annotations, and add whichever needs to be added. What I understand is that only the regex output is used to represent a task, is this correct?
